#!/bin/bash

for study_name in 'container' 'native'
do
   for s in $(seq 3)
   do
      for i in $(seq 10)
      do
	 case $study_name in
	    native)
	       tclsh default_richards.tcl $i $i 1 ${study_name} $s
	       ;;

	    container)
	       tclsh default_richards.tcl $i $i 1 ${study_name} $s
	       ;;
	       
	 esac
      done
   done
done
