#!/bin/bash

source /global/homes/u/u9563/global-parflow/perlmutter-v3.9.0-2023-10-24/setenv.sh

for study_name in 'container' 'native'
do
   for s in $(seq 3)
   do
      for i in $(seq 1)
      do
	 case $study_name in
	    native)
	       tclsh default_richards.tcl $i $i 1 ${study_name} $s
	       ;;

	    container)
	       tclsh default_richards.tcl $i $i 1 ${study_name} $s
	       ;;
	       
	 esac
      done
   done
done
