name: Build ParFlow

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true
      matrix:
        config:
        - {
            name: "Ubuntu 18.04"
            os: ubuntu-18.04,
            cc: "gcc", cxx: "g++"
	    backend: none
	    python: false
          }
        - {
            name: "Ubuntu 18.04 Python"
            os: ubuntu-18.04,
            cc: "gcc", cxx: "g++"
	    backend: none
	    python: true
          }
        - {
            name: "Ubuntu 16.04"
            os: ubuntu-16.04,
            cc: "gcc", cxx: "g++"
	    backend: none
	    python: false
          }

    steps:
    - uses: actions/checkout@v2

    - name: Package Install
      run: sudo apt install gfortran libhdf5-openmpi-dev libhdf5-openmpi-100 hdf5-helpers tcl-dev tk-dev

    - name: Directory Setup
      run: |
        mkdir -p $PWD/install
        echo "PARFLOW_DIR=$PWD/install" >> $GITHUB_ENV
        echo "Setting PARFLOW_DIR=$PWD/install"

    - name: CMake Install
      run: |
        wget --no-check-certificate http://cmake.org/files/v3.14/cmake-3.14.0-Linux-x86_64.tar.gz
        tar -xf cmake-3.14.0-Linux-x86_64.tar.gz
        echo "$PWD/cmake-3.14.0-Linux-x86_64/bin/" >> $GITHUB_PATH

    - name: SILO Install
      run: |
        wget https://wci.llnl.gov/content/assets/docs/simulation/computer-codes/silo/silo-4.10.2/silo-4.10.2.tar.gz
        tar -xf silo-4.10.2.tar.gz
        cd silo-4.10.2
        ./configure --disable-silex --disable-hzip --disable-fpzip --prefix=$PARFLOW_DIR
        make install 

    - name: HYPRE Install
      run: |
        wget https://github.com/hypre-space/hypre/archive/v2.18.2.tar.gz
        tar -xf v2.18.2.tar.gz 
        cd hypre-2.18.2/src 
        ./configure --prefix=$PARFLOW_DIR
        make install 

    - name: ParFlow CMake Configure
      run: cmake -Bbuild -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}  -DCMAKE_C_FLAGS='-Wall -Werror -Wno-unused-result -Wno-unused-function' -DPARFLOW_ENABLE_TIMING=TRUE -DPARFLOW_AMPS_LAYER=mpi1 -DMPIEXEC_POSTFLAGS='--oversubscribe' -DPARFLOW_ACCELERATOR_BACKEND=${{ matrix.config.backend }} -DPARFLOW_AMPS_SEQUENTIAL_IO=true -DPARFLOW_HAVE_CLM=ON -DHYPRE_ROOT=$PARFLOW_DIR -DSILO_ROOT=$PARFLOW_DIR -DPARFLOW_ENABLE_PYTHON=${{ matrix.config.python }} -DPARFLOW_PYTHON_VIRTUAL_ENV=${{ matrix.config.python }} -DCMAKE_INSTALL_PREFIX=$PARFLOW_DIR

    - name: ParFlow CMake Build
      run: (cd build; make install)

    - name: ParFlow CTest
      run: (cd build; ctest)
