name: ParFlow CI Test

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true
      matrix:
        config:
        - {
            name: "Ubuntu 18.04 CUDA Build", artifact: "linux-gcc.tar.xz",
            os: ubuntu-18.04,
            cc: "gcc", cxx: "g++",
            python: "false",
            backend: "cuda",
            cudaos: 'ubuntu1804'
          }
    steps:
    - uses: actions/checkout@v2

    - name: Package Install
      run: sudo apt install gfortran libhdf5-openmpi-dev libhdf5-openmpi-100 hdf5-helpers tcl-dev tk-dev

    - name: Cache dependencies for CUDA build
      if: matrix.config.backend == 'cuda'
      uses: actions/cache@v2
      id: cache-parflow-cuda-dependencies
      env:
        cache-name: cache-parflow-cuda-dependencies
        cache-parflow-cuda-hit: ${{steps.cache-parflow-cuda-dependencies.outputs.cache-hit}}
      with:
        path: ~/depend
        key: ${{ matrix.config.backend }}-build-${{ env.cache-name }}

    - name: Directory Setup
      run: |
        mkdir -p $PWD/install
        echo "PARFLOW_DIR=$PWD/install" >> $GITHUB_ENV
        echo "Setting PARFLOW_DIR=$PWD/install"
        mkdir -p $PWD/depend
        echo "PARFLOW_DEP_DIR=$PWD/depend" >> $GITHUB_ENV
        echo "Setting PARFLOW_DEP_DIR=$PWD/depend"

    - name: CMake Install
      env:
        CACHE_HIT: ${{steps.cache-parflow-cuda-dependencies.outputs.cache-hit}}
      run: |
        if [[ "$CACHE_HIT" != 'true' ]]; then
          wget --no-check-certificate http://cmake.org/files/v3.14/cmake-3.14.0-Linux-x86_64.tar.gz
          tar -xf cmake-3.14.0-Linux-x86_64.tar.gz
        fi
        echo "$PWD/cmake-3.14.0-Linux-x86_64/bin/" >> $GITHUB_PATH

    - name: CUDA Install
      if: matrix.config.backend == 'cuda'
      run: |
        CUDA_SHORT=10.1
        CUDA_VER=10.1.105-1
        wget http://developer.download.nvidia.com/compute/cuda/repos/${{ matrix.config.cudaos }}/x86_64/cuda-repo-${{ matrix.config.cudaos }}_${CUDA_VER}_amd64.deb
        sudo dpkg -i cuda-repo-${{ matrix.config.cudaos }}_${CUDA_VER}_amd64.deb;
        sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/${{ matrix.config.cudaos }}/x86_64/7fa2af80.pub
        sudo apt update -qq
        sudo apt install -y cuda-core-${CUDA_SHORT/./-} cuda-cudart-dev-${CUDA_SHORT/./-} cuda-nvtx-${CUDA_SHORT/./-}
        export CUDA_HOME=/usr/local/cuda-${CUDA_SHORT}
        echo "CUDA_HOME=${CUDA_HOME}" >> $GITHUB_ENV
        export LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}
        echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}" >> $GITHUB_ENV
        export LIBRARY_PATH=${CUDA_HOME}/lib64/stubs
        echo "LIBRARY_PATH=${LIBRARY_PATH}" >> $GITHUB_ENV
        echo "${CUDA_HOME}/bin" >> $GITHUB_PATH
        echo "CUDA_LINK_FLAGS=\"-L${CUDA_HOME}/lib64 -lcuda\"" >> $GITHUB_ENV

    - name: UCX
      if: matrix.config.backend == 'cuda'
      env:
        CACHE_HIT: ${{steps.cache-parflow-cuda-dependencies.outputs.cache-hit}}
      run: |
        if [[ "$CACHE_HIT" != 'true' ]]; then
          sudo apt install -y autoconf automake libtool
          wget https://github.com/openucx/ucx/releases/download/v1.8.0-rc1/ucx-1.8.0.tar.gz
          tar -xf ucx-1.8.0.tar.gz
          cd ucx-1.8.0
          ./contrib/configure-release --with-cuda=$CUDA_HOME --with-java=no --disable-numa --prefix=$PARFLOW_DEP_DIR 
          make -j 2 install
        fi

    - name: RMM Install
      env:
        CACHE_HIT: ${{steps.cache-parflow-cuda-dependencies.outputs.cache-hit}}
      if: matrix.config.backend == 'cuda'
      run: |
        if [[ "$CACHE_HIT" != 'true' ]]; then
          git clone -b branch-0.10 --single-branch --recurse-submodules https://github.com/rapidsai/rmm.git
          cd rmm
          cmake . -DCMAKE_INSTALL_PREFIX=$PARFLOW_DEP_DIR
          make -j 2 install
        fi
        echo "RMM_FLAGS=-DRMM_ROOT=$PARFLOW_DEP_DIR" >> $GITHUB_ENV     

    - name: OpenMPI Install for CUDA
      env:
        CACHE_HIT: ${{steps.cache-parflow-cuda-dependencies.outputs.cache-hit}}
      if: matrix.config.backend == 'cuda'
      run: |
        if [[ "$CACHE_HIT" != 'true' ]]; then
          wget https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.3.tar.gz
          tar -xf openmpi-4.0.3.tar.gz
          cd openmpi-4.0.3
          ./configure --with-cuda=$CUDA_HOME --with-ucx=$PARFLOW_DEP_DIR
          sudo make -j 2 install
          cd ..
        fi
        sudo ldconfig

    - name: HYPRE Install
      env:
        CACHE_HIT: ${{steps.cache-parflow-cuda-dependencies.outputs.cache-hit}}
      run: |
        if [[ "$CACHE_HIT" != 'true' ]]; then
          wget https://github.com/hypre-space/hypre/archive/v2.18.2.tar.gz
          tar -xf v2.18.2.tar.gz 
          cd hypre-2.18.2/src 
          ./configure --prefix=$PARFLOW_DEP_DIR
          make -j 2 install
        fi

    - name: ParFlow CMake Configure
      run: |
        echo "-DCMAKE_EXE_LINKER_FLAGS= $CUDA_LINK_FLAGS"
        cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }} -DCMAKE_C_FLAGS="-Wall -Werror -Wno-unused-result -Wno-unused-function" -DCMAKE_EXE_LINKER_FLAGS="$CUDA_LINK_FLAGS" -DPARFLOW_ENABLE_TIMING=TRUE -DPARFLOW_AMPS_LAYER=mpi1 -DMPIEXEC_POSTFLAGS='--oversubscribe' -DPARFLOW_ACCELERATOR_BACKEND=${{ matrix.config.backend }} -DPARFLOW_AMPS_SEQUENTIAL_IO=true -DPARFLOW_HAVE_CLM=ON -DHYPRE_ROOT=$PARFLOW_DEP_DIR -DSILO_ROOT=$PARFLOW_DEP_DIR -DPARFLOW_ENABLE_PYTHON=${{ matrix.config.python }} -DPARFLOW_PYTHON_VIRTUAL_ENV=${{ matrix.config.python }} $RMM_FLAGS -DCMAKE_INSTALL_PREFIX=$PARFLOW_DIR

    - name: Debug
      run: |
        echo $PATH
        printenv
        which nvcc

    - name: ParFlow CMake Build
      run: (cd build; make -j 2 install)


    # Can't test with CUDA
    - name: ParFlow CTest
      if: matrix.config.cc != 'cuda'
      run: (cd build; ctest)
